version: "3.8"
services:
  db:

    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'ecommercedb'
      POSTGRES_PORT: 5432
    container_name: EcommerceApi_postgresql_container

  app:
    build: .
    volumes:
      - .:/EcommerceApi
    ports:
      - 8808:8808
    image: app:EcommerceApi_image
    container_name: EcommerceApi_container
    depends_on:
      - db
