version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/EcommerceApi
    ports:
      - 8808:8808
    image: app:EcommerceApi_image
    container_name: EcommerceApi_container
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8808"
  
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:81
    depends_on:
      - app